config/routes.rb
Rails.application.routes.draw do
	
	resources :events

  # 外卡路由
  # ex: http://localhosts:3000/events/index
  # 路由收到 request 後，會執行 "events" controller 中的 "index" action
  # 且照慣例會使用同名的 "index".html.erb 回傳 response 給使用者
  # match ':controller(/:action(/:id(.:format)))', :via => :all
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  # 為了避免活動的名稱與描述在寫入資料庫時是空的，在model針對這兩個欄位進行驗證
  # 驗證column :name, :description 輸入資料庫的時候不能是空的
  validates_presence_of :name
  validates_presence_of :description
end

# note: validate 會觸發只有在以下幾個method save , save! , update , update! , create , create!
# validate 請參考 https://ihower.tw/rails4/activerecord-lifecycle.html  Validation 資料驗證

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # view對應的規則  會是app/views/<controller>/<action>.html.erb

before_action :set_event, :only => [:show, :edit, :update, :destroy]

  # events
  # events/index
  # action 是 index 對應的view會是 app/views/events/index.html.erb
  def index
    # 查詢所有的活動的資料，將查詢的結果放到一個實例變數（instance variable）
    # 查詢所有的資料：透過model進行查詢。
    # 變數命名建議是可以看得出內容的命名，例如events容易理解裡面是由很多個event組成。
    @events = Event.page(params[:page]).per(10)
  end

  # events/new
  # action 是 new 對應的view會是 app/views/events/new.html.erb
  def new
    # 透過Event model 產生一個空的Event物件，並將它存到實例變數（instance variable）中，view 中才可以使用。
    @event = Event.new
  end

  # events/create
  # 這個action是接收new表單post過來的東西後進行新增資料
  # !!!! action create並沒有對應的view 新增完成後這個action 是進行轉跳
  def create
    # 處理strong parameter
    # https://ihower.tw/rails4/basic.html 參考 新增資料 章節
    @event = Event.new(event_params)
    # 透過save的方法存入資料庫
    if @event.save
    # 轉跳到show
    flash[:notice] = "新增成功"
    redirect_to event_path(@event)
    # action show是顯示一筆資料 因此redirect_to 除了告訴rails 要去哪個action外
    # 還需要帶入:id => @event 告訴rails是哪一筆資料
    else
      render :new
    end
  end

  # events/show/:id
  # action 是 show 對應的view 是 app/views/events/show.html.erb
  def show
    @pagename = @event.name
  end

  # events/edit/:id
  # action 是 edit 對應的view 是 app/views/events/edit.html.erb
  def edit
  end

  # events/update/:id
  # 這個action是接收edit表單post過來的東西後進行資料資料
  # !!!! action update並沒有對應的view 修改完成後這個action 是進行轉跳
  def update
    # @event是透過Event查詢出來的物件，代表資料表的一個row。
    # 可以使用instance method，update去更新內容。
    # ex: @event.update(:name => "foo" , :description => "bar")
    # 但現在update的資料是從表單post進來
    # 因此處理strong parameter
    if @event.update(event_params)
    flash[:notice] = "編輯成功"
    redirect_to event_path(@event)
    # 轉跳到show
    # action show是顯示一筆資料 因此redirect_to 除了告訴rails 要去哪個action外
    # 還需要帶入:id => @event 告訴rails是哪一筆資料
    else
      render :edit
    end
  end

  # events/destroy/:id
  # !!!! action destroy並沒有對應的view 刪除完成後這個action 是進行轉跳
  def destroy
    @event.destroy
    # 利用物件的方法刪除該筆資料
    flash[:alert] = "刪除成功"
    redirect_to events_path
    # 轉跳到index，redirect_to
  end

  private
  def set_event
    # 藉由Event model，利用params[:id]找到該id在資料表中的那一個row，
    # @event會是一個Event產出來的物件，代表資料表中的一個row。
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name,:description,:is_public,:capacity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
    <ul>
        <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= f.label :name %>
<%= f.text_field :name, :class => "form-control" %>
<!--為 name 建立一個text_field的輸入框 跟new不同的是 rails很聰明的會把資料庫的內容先帶入-->

<%= f.label :description %>
<%= f.text_area :description, :class => "form-control" %>
<!--為 description 建立一個text_area的輸入框 跟new不同的是 rails很聰明的會把資料庫的內容先帶入-->
<br>
<%= f.label :is_public %>
<%= f.check_box :is_public %>
<br>
<br>
<%= f.label :capacity %>
<%= f.text_field :capacity, :class => "form-control" %>
<br>
<%= f.submit :class => "btn btn-success" %>
<!--使用submit方法建立一個送出的按鈕-->

<%= link_to "Index" , events_path, :class => "btn btn-default" %>

app/views/events/edit.html.erb
<!--
利用rails 提供的helper form_for產生表單
form_for後第一個空格填入一個model產生的物件，這邊是由controller傳遞過來的@event
url後帶入一個hash，rails 會依據給的controller與action產生對應的網站，修改資料的action我們預計使用update
另外需要補上想要對哪一個id進行修改
form_for會透過這些參數替我們產生適當的 form tag
-->
<%= form_for @event, :url => event_path(@event), :method => :patch do |f| %>
    
<%= render :partial => "form", :locals => { :f => f } %>

<% end %>

<!--
建議完成可以直接到瀏覽器
http://localhost:3000/events/edit/:id
這個:id的位置可以放資料庫已經存在的id ex: http://localhost:3000/events/edit/1
看rails產生表單的內容對應的html程式碼
-->

app/views/events/index.html.erb
<h1>Event List</h1>

<table class="table">
  <!--將傳遞過來的實例變數(instance variable)，透過array的方法each一個一個放到black區塊執行-->
  <!--執行rails 語法的區塊有分有 = 跟沒有 = 兩種，差異是會不會把內容印出來。-->
  <tr>
    <th>Event</th>
    <th>Details</th>
    <th>Edit</th>
    <th>DELETE</th>
  </tr>
  <% @events.each do |event| %>
      <tr>
        <!--印出每一個event的名字 每一個event的column name是一個方法 例如 event.description-->
        <td> <%= event.name %> </td>
        <!-- 為每一個event 利用 URL輔助方法(link_to) 製作一個 文字超連結 -->
        <!-- 做一個超連結 show controller是events，action是show，id是當前的event-->
        <td><%= link_to "Show" , event_path(event), :class => "btn btn-primary" %></td>
        <!--做一個超連結 edit controller是events，action是edit，id是當前的event-->
        <td><%= link_to "Edit" , edit_event_path(event), :class => "btn btn-default" %></td>
        <!--做一個超連結 destroy controller是events，action是destroy，id是當前的event-->
        <td><%= link_to "DELETE" , event_path(event), :method => :delete , :class => "btn btn-danger"%></td>
      </tr>
  <% end %>
</table>

<!--
利用rails URL輔助方法 製作一個 文字超連結
link_to "New Event", :controller => "events" , :action => "new"
-->
<%= link_to "New Event" , new_event_path , :class => "btn btn-success" %>
<br>
<br>
<%= paginate @events %>

app/views/events/new.html.erb
<!--
利用rails 提供的helper form_for產生表單
form_for後第一個空格填入一個model產生的物件，這邊是由controller傳遞過來的@event
url後帶入一個hash，rails 會依據給的controller與action產生對應的網站，新增資料的action我們預計使用create
form_for會透過這些參數替我們產生適當的 form tag
-->
<%= form_for @event, :url => events_path do |f| %>

<%= render :partial => "form", :locals => { :f => f } %>

<% end %>

<!--
建議完成可以直接到瀏覽器
http://localhost:3000/events/new
看rails產生表單的內容對應的html程式碼
-->

app/views/events/show.html.erb
<h1>This is event No.<%= @event[:id] %></h1>
<!--
controlerr中實例變數（instance variable）
顯示這一筆資料的內容
ex:
@event.name
@event.description
@event.is_public
@event.capacity
-->
<ul>
	<li>
		<p>Name of event: <%= @event.name %></p>
	</li>
	<li>
		<p>Description: <%= @event.description %></p>
	</li>
	<li>
		<p>Is public: <%= @event.is_public %></p>
	</li>
	<li>
		<p>Capacity: <%= @event.capacity %></p>
	</li>
</ul>

<%= link_to "Index" , events_path , :class => "btn btn-default"%>
<!--做一個超連結 show controller是events，action是index-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= @pagename || AcWebcampCrudPractice %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% if flash[:notice].present? %>
            <div class="alert alert-success" role="alert">
              <%= flash[:notice] %></p>
            </div>
          <% end %>
          
          <% if flash[:alert].present? %>
            <div class="alert alert-danger" role="alert">
              <%= flash[:alert] %>
            </div>
          <% end %>
          <%= yield %>          
        </div>
      </div>
    </div>

  </body>
</html>